name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-install:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out OQpy
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install OQpy using pip
        run: pip install .

      - name: Import OQpy and print version
        run: python -c "import oqpy; print(oqpy.__version__)"

  check-style:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out OQpy
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --frozen

      - name: Run black
        run: uv run --python ${{ matrix.python-version }} make check-format

      - name: Run mypy
        run: uv run --python ${{ matrix.python-version }} make check-mypy

      - name: Run pylint
        run: uv run --python ${{ matrix.python-version }} make check-pylint

      - name: Run pydocstyle
        run: uv run --python ${{ matrix.python-version }} make check-pydocstyle

      - name: Run cffconvert
        run: uv run --python ${{ matrix.python-version }} make check-citation

      - name: Build and check docs
        run: uv run --python ${{ matrix.python-version }} make docs

  check-tests:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out OQpy
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --python ${{ matrix.python-version }} --frozen

      - name: Run pytest
        run: uv run --python ${{ matrix.python-version }} make check-tests
